services:
  back:
    image: orion-microcrm-back:latest
    build:
      context: .
      target: back
    labels:
      microcrm_logs: "true"
      microcrm_service: back
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "8081:8081"

  front:
    image: orion-microcrm-front:latest
    build:
      context: .
      target: front
    labels:
      microcrm_logs: "true"
      microcrm_service: front
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - back
    ports:
      - "80:80"
      - "443:443"

  standalone:
    profiles:
      - standalone
    image: orion-microcrm-standalone:latest
    build:
      context: .
      target: standalone
    ports:
      - "80:80"
      - "443:443"
      - "8081:8081"
